# -*- coding: utf-8 -*-
"""Raport_Dodatkowy_SikorskiDawid_291951.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H_czdnubB0REvQFk4PYCT9_5QcU2K4oi
"""

!pip install sklearn_som

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn_som.som import SOM
from scipy import stats

index = 291951
plt.rcParams['figure.figsize'] = [15, 15]

dane = pd.read_csv('https://gist.githubusercontent.com/sikor272/3031999a870e7760824de89d663b011d/raw/ba3db6577e8d55a2d8133b96b6e24c64d11a6399/churn_pl_wybrane.csv', sep=',')

dane.columns

columns = ['Czaswspolpracy', 'Liczbawiadomosci', 'Dzienminuty', 'Dzienrozmowy',
       'Wieczorminuty', 'Wieczorrozmowy', 'Nocminuty', 'Nocrozmowy',
       'Miedzynarodoweminuty', 'Miedzynarodowerozmowy', 'LiczbarozmowzBOK',
       'Planmiedzy01', 'Pocztagl01']

"""#Macierz Histogramów
Wymagane aby kolumny były numeryczne
"""

dane[columns].hist()
plt.show()

"""#Sieć kohonena"""

dane_som = dane[columns]
dane_som = stats.zscore(dane_som) # return np.array

som = SOM(m = 3, n = 3, dim = len(columns))
som.fit(dane_som)

som.cluster_centers_

som.transform(dane_som) # Odległość Euklidesowa od obserwacji do każdego środka klastra

dane['klaster'] = som.predict(dane_som)

dane.head(10)

"""#Liczebność klastrów"""

dane.groupby('klaster').size().reset_index(name='ilość')

"""#Średnie dla klastrów"""

dane.groupby('klaster')[columns + ['Rezygnacja']].mean().reset_index()